version: '3.6'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always
    command: '--server-id=0 --log-bin=mysql-bin --binlog-format=ROW --binlog-row-image=FULL --gtid_mode=ON --enforce-gtid-consistency'
    ports:
      - "3306:3306"
    volumes:
      - "./mysqldata:/var/lib/mysql"
  setup:
    image: mysql:5.7
    entrypoint: bash
    command: '-xc "mysql -h mysql -u root < /setup-test.sql"'
    volumes:
      - "./setup-test.sql:/setup-test.sql:ro"
    links:
      - mysql:mysql
    depends_on:
      - mysql
  mysqlbinlog:
    image: mysql:5.7
    entrypoint: mysqlbinlog
    command: '-vv --base64-output=DECODE-ROWS /mysql/mysql-bin.000003'
    volumes:
      - "./mysqldata:/mysql:ro"
    depends_on:
      - mysql
